Repository DiamondLightSource/xchemlab, pull requests merged in 2023-11, with the labels that each got.

#220 [`the_paginator`] Add SQL string tests
  backend/the_paginator/src/lib.rs
Labels: rust

#221 [`graphql_types`] Remove `graphql_types` crate
  backend/Cargo.lock
  backend/Cargo.toml
  backend/Dockerfile
  backend/graphql_types/Cargo.toml
  backend/graphql_types/README.md
  backend/graphql_types/src/lib.rs
  backend/pin_packing/Cargo.toml
  backend/pin_packing/src/resolvers/crystal.rs
  backend/pin_packing/src/resolvers/mod.rs
  backend/targeting/Cargo.toml
  backend/targeting/src/resolvers/image.rs
  backend/targeting/src/resolvers/mod.rs
  backend/targeting/src/resolvers/prediction.rs
Labels: rust, docker

#223 frontend docker config
  .devcontainer/Dockerfile.frontend
  .devcontainer/docker-compose.yaml
Labels: enhancement
