Repository DiamondLightSource/xchemlab, pull requests merged in 2023-10, with the labels that each got.

#125 Fix pre-commit hooks
  .pre-commit-config.yaml
Labels: bug

#126 Store ONNX files in Git LFS
  .gitattributes
Labels: bug

#128 Remove `.env` file mount from OPA dev container
  .devcontainer/docker-compose.yaml
Labels: enhancement

#127 Use templating for pin-packing opa url
  charts/xchemlab/Chart.lock
  charts/xchemlab/Chart.yaml
  charts/xchemlab/charts/pin-packing/Chart.yaml
  charts/xchemlab/charts/pin-packing/templates/_helpers.tpl
  charts/xchemlab/charts/pin-packing/templates/deployment.yaml
  charts/xchemlab/charts/pin-packing/values.yaml
  charts/xchemlab/values.yaml
Labels: enhancement

#131 [`clap_for_s3`] Make force path style a `Clap` action
  backend/clap_for_s3/src/lib.rs
Labels: enhancement, rust

#133 Pass chimp chomp `RabbitMQ` URL in as env var
  charts/xchemlab/Chart.lock
  charts/xchemlab/Chart.yaml
  charts/xchemlab/charts/chimp-chomp/Chart.yaml
  charts/xchemlab/charts/chimp-chomp/templates/deployment.yaml
Labels: enhancement, helm

#134 [`chimp_protocol`] Return predictions as integers
  backend/chimp_chomp/src/postprocessing.rs
  backend/chimp_chomp/src/well_centering.rs
  backend/chimp_protocol/src/lib.rs
Labels: enhancement, rust

#135 [`chimp_chomp`] Download images from URL
  backend/Cargo.lock
  backend/Cargo.toml
  backend/chimp_chomp/Cargo.toml
  backend/chimp_chomp/src/image_loading.rs
  backend/chimp_chomp/src/jobs.rs
  backend/chimp_chomp/src/main.rs
  backend/chimp_protocol/Cargo.toml
  backend/chimp_protocol/src/lib.rs
  backend/targeting/src/resolvers/image.rs
Labels: enhancement, rust

#136 [`graphql_endpoints`] Forward authoriztion token in `GraphQLSubscription`
  backend/Cargo.lock
  backend/graphql_endpoints/Cargo.toml
  backend/graphql_endpoints/src/lib.rs
Labels: bug, rust

#138 Consistently name plate & well in across API
  backend/chimp_chomp/src/jobs.rs
  backend/chimp_chomp/src/main.rs
  backend/chimp_protocol/src/lib.rs
  backend/pin_packing/src/resolvers/crystal.rs
  backend/pin_packing/src/tables/crystal.rs
  backend/targeting/src/resolvers/image.rs
  backend/targeting/src/resolvers/prediction.rs
  backend/targeting/src/tables/image.rs
  backend/targeting/src/tables/prediction.rs
Labels: enhancement, rust

#153 changed backend dependabot dir to /backend/
  .github/dependabot.yml
Labels: bug, dependencies

#190 changed root docker dependabot check to /backend/
  .github/dependabot.yml
Labels: bug, dependencies
